### PR TITLE
feat: add .toBeJsonMatching(expectation) matcher

### PR DESCRIPTION
**Pull request by Belema**
### What

This adds support for a new custom matcher `.toBeJsonMatching(...)`.

### Why

This matcher is useful when one wants to check that a function has been called with a JSON string that satisfies some constraints,

```js
expect(fn).toHaveBeenCalledWith(
  expect.toBeJsonMatching({ key1: 'value1' })
);
```

### Housekeeping

- [x] Unit tests
- [x] Documentation is up to date
- [x] No additional lint warnings
- [x] [Typescript definitions](https://github.com/jest-community/jest-extended/blob/main/types/index.d.ts) are added/updated where relevant

### CODE REVIEW

**Comment by SimenB** [comment]
@Belema I like this - could you resolve the conflicts?

**Comment by Belema** [comment]
> @Belema I like this - could you resolve the conflicts?

@SimenB, I have just rebased the changes.

**Comment by SimenB** [comment]
Make sure to add a changeset so this triggers a release

**Comment by Belema** [comment]
> Make sure to add a changeset so this triggers a release

@SimenB I have done so, and accidentally deleted my branch (which closed this PR). I have opened a new one #606 for it.

**Pull request closed without merging**
