### PR TITLE
fix: export CustomMatchers interface for declartion merging

### PR DESCRIPTION
**Pull request by cdierkens**
### What

export CustomMatchers interface for declartion merging

### Why

https://github.com/jest-community/jest-extended/issues/652

### Housekeeping

- [x] Unit tests
- [x] Documentation is up to date
- [x] No additional lint warnings
- [x] [Typescript definitions](https://github.com/jest-community/jest-extended/blob/main/types/index.d.ts) are added/updated where relevant

### CODE REVIEW

**Review by SimenB — APPROVED** [review]
thanks!

**Comment by SimenB** [comment]
Huh, unsure why this change breaks the typecheck 🤔

**Comment by cdierkens** [comment]
> Huh, unsure why this change breaks the typecheck 🤔

@SimenB I'll try updating the branch. Maybe there's something else I can look into if that doesn't work?

**Comment by cdierkens** [comment]
I'll run the type checking locally and do a bit more research on how other libraries go about declaration merging.

**Comment by keeganwitt** [comment]
I tried adding a dependency on `@types/jest` and adding `/// <reference types="jest" />`, but that didn't help.

**Comment by keeganwitt** [comment]
I'm not sure if this is the right way to fix this, but this way passes the check.

@cdierkens can you confirm whether this still works as a patch for you?

**Comment by cdierkens** [comment]
@keeganwitt I was able to get declaration merging working with the existing types!

```ts
import type CustomMatchers from "jest-extended";
import "vitest";

declare module "vitest" {
  interface Assertion<T = any> extends CustomMatchers<T> {}
  interface AsymmetricMatchersContaining<T = any> extends CustomMatchers<T> {}
  interface ExpectStatic extends CustomMatchers<T> {}
}

```

**Pull request closed without merging**
