### PR TITLE
Declare matchers for use with expect.not.MATCHER (#385)

### PR DESCRIPTION
**Pull request by dharkness**
### What

Move asymmetric matcher declarations to a new `AsymmetricMatchers` interface and extend that to add matchers to `Expect` and `InverseAsymmetricMatchers`.

### Why

This provides autocompletion when using `expect.not`, for example:

```
const value = {
  name: 'foobar',
};
expect(value).toEqual({
  name: expect.not.toStartWith('bar')
});
```

### Notes

This may not play nicely with actual TypeScript projects, but I do not have experience with that to verify. I didn't add any unit tests since I didn't change any code. TypeScript tests would be very useful for the project as a whole.

### Housekeeping

- [ ] Unit tests
- [x] Documentation is up to date
- [x] No additional lint warnings
- [x] [Typescript definitions](https://github.com/jest-community/jest-extended/blob/main/types/index.d.ts) are added/updated where relevant

### CODE REVIEW

**Comment by keeganwitt** [comment]
To give me a little more context on this, what autocompletion was this helping enable? With TypeScript projects in In VS Code?

**Comment by rluvaton** [comment]
not related to vs code but typescript not compiling as he thinks these matchers can't be negated using `.not.*`

**Comment by keeganwitt** [comment]
I believe the reason this is happening is because of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/658b4ded756f0c98e1a22e9592014c3c6bc4323a/types/jest/index.d.ts#L729.

**Comment by SimenB** [comment]
https://github.com/jest-community/jest-extended/releases/tag/v3.0.2

**Pull request merged**
