### PR TITLE
feat: upgrade to jest v28

### PR DESCRIPTION
**Pull request by G-Rath**
### What

Updates to jest v28

### Why

Cause @SimenB didn't look into it over the weekend 😄 

### Notes

Resolves #439

### Housekeeping

- [x] Unit tests
- [x] Documentation is up to date
- [x] No additional lint warnings
- [x] [Typescript definitions](https://github.com/jest-community/jest-extended/blob/main/types/index.d.ts) are added/updated where relevant

### CODE REVIEW

**Comment by SimenB** [comment]
😀

Should update https://github.com/jest-community/jest-extended/blob/06b23dfb1de75e693aa40fd5fd0012af143e15c8/.github/workflows/ci.yaml#L19 as well

**Comment by G-Rath** [comment]
Bah it was working fine on my local 😭

Will fix tomorrow morning

**Comment by SimenB** [comment]
Let's do the same here as in https://github.com/facebook/jest/pull/12935, it's less painful than dealing with the plugin

**Comment by SimenB** [comment]
Thanks @G-Rath!

**Pull request merged**
