### PR TITLE
Update docs to use setupFilesAfterEnv

### LINKED ISSUE #192: Update docs to remove usage of deprecated config key setupTestFrameworkScriptFile
**Feature Request**

Description: In the last release of Jest `24.0.0` the configuration for scripts to run before tests are changed, deprecating `setupTestFrameworkScriptFile: String` in favor of `setupFilesAfterEnv: []`

See: 
- [Jest docs](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)
- [The PR introducing the change](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)

Possible solution: Just the docs (README) should be updated to use the new API

### PR DESCRIPTION
**Pull request by abdelrahman-elkady**
### What

**Feature** update docs to use `setupFilesAfterEnv`, resolves #192 

### Why
`setupTestFrameworkScriptFile` is deprecated in jest `24.0.0`, see #192

### Housekeeping

- [x] Unit tests
- [x] Documentation is up to date
- [x] No additional lint warnings
- [x] Add yourself to contributors list (`yarn contributor`)
- [x] [Typescript definitions](https://github.com/jest-community/jest-extended/blob/master/types/index.d.ts) are added/updated where relevant

### CODE REVIEW

**Comment by abdelrahman-elkady** [comment]
@benjaminkay93 Sooo, Shouldn't that actually be merged ? :upside_down_face:

**Comment by benjaminkay93** [comment]
I don't yet have the ability or else I would merge it myself :)

**Comment by abdelrahman-elkady** [comment]
@benjaminkay93 Sorry, just came across #205, hopefully this project gets more attention and maintenance soon :))

**Comment by mattphillips** [comment]
Sorry @abdelrahman-elkady I accidentally nuked the commits on this branch and can no longer push them back - I've re-opened this in #215

**Pull request closed without merging**
