### PR TITLE
fix: add missing types for toPartiallyContain

### PR DESCRIPTION
**Pull request by idan-at**
### What
Missing types for a newly added matcher.

### CODE REVIEW

**Review by SimenB — COMMENTED** [review]
https://github.com/jest-community/jest-extended/blob/5083e49dc934cfea439346eb8c72a2d842edd9ec/types/index.d.ts#L417 as well, no?

**Comment by idan-at** [comment]
> as well, no?

@SimenB of course - https://github.com/jest-community/jest-extended/pull/392/commits/802084c51caadc86927fee93f9d72f2a3710afc4

**Review by SimenB — APPROVED** [review]
thanks!

**Comment by Smrtnyk** [comment]
any chance we  can have a release?
I want to use this matcher but ts complains and I don't feel like creating my own type if release is coming soon?

**Pull request merged**
